########## BoCA component makefile ##########

# Change these variables to fit your project:
TARGET	  = tagedit
TYPE	  = extension
VERSION	  = 1.0

BOCA_PATH = ../../..

# Enter object files here:
OBJECTS	  = advanced/layer_edit_number.o advanced/layer_edit_text.o advanced/layer_tag_advanced.o basic/layer_tag_basic.o basic/layer_tag_details.o basic/layer_tag_other.o layer.o tagedit.o tagspec.o utilities.o

# Enter additional library dependencies here
LIBS	  =

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
CLEANCMD1 =
CLEANCMD1 =

## Do not change anything below this line. ##

include $(BOCA_PATH)/Makefile-directories
include $(BOCA_PATH)/Makefile-commands
