########## BoCA directory makefile ##########

BOCA_PATH = ../..

include $(BOCA_PATH)/Makefile-options

all:
	cd donate && $(MAKE)
	cd protocols && $(MAKE)
	cd statustime && $(MAKE)
	cd tagedit && $(MAKE)
	cd youtube && $(MAKE)

clean:
	cd donate && $(MAKE) clean
	cd protocols && $(MAKE) clean
	cd statustime && $(MAKE) clean
	cd tagedit && $(MAKE) clean
	cd youtube && $(MAKE) clean
