########## BoCA directory makefile ##########

all:
	cd donate && make
	cd protocols && make
	cd statustime && make
	cd tagedit && make
	cd youtube && make

clean:
	cd donate && make clean
	cd protocols && make clean
	cd statustime && make clean
	cd tagedit && make clean
	cd youtube && make clean
