########## BoCA component makefile ##########

# Change these variables to fit your project:
TARGET	  = mac
TYPE	  = decoder
VERSION	  = 1.0

BOCA_PATH = ../../..

# Enter object files here:
OBJECTS	  = dllinterface.o mac_in.o

# Enter additional defines here:
DEFINE	  = -DNO_DEFINE_ENVIRONMENT_VARIABLES -D__forceinline=inline

# Enter additional library dependencies here:
LIBS	  =

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
CLEANCMD1 =
CLEANCMD2 =
INSTCMD1  =
INSTCMD2  = 
UINSTCMD1 =
UINSTCMD2 =

## Do not change anything below this line. ##

include $(BOCA_PATH)/Makefile-directories
include $(BOCA_PATH)/Makefile-commands
