########## BoCA directory makefile ##########

all:
	cd decoder && $(MAKE)
	cd deviceinfo && $(MAKE)
	cd dsp && $(MAKE)
	cd encoder && $(MAKE)
	cd extension && $(MAKE)
	cd other && $(MAKE)
	cd output && $(MAKE)
	cd tagger && $(MAKE)

clean:
	cd decoder && $(MAKE) clean
	cd deviceinfo && $(MAKE) clean
	cd dsp && $(MAKE) clean
	cd encoder && $(MAKE) clean
	cd extension && $(MAKE) clean
	cd other && $(MAKE) clean
	cd output && $(MAKE) clean
	cd tagger && $(MAKE) clean

install:
	cd decoder && $(MAKE) install
	cd deviceinfo && $(MAKE) install
	cd dsp && $(MAKE) install
	cd encoder && $(MAKE) install
	cd extension && $(MAKE) install
	cd other && $(MAKE) install
	cd output && $(MAKE) install
	cd tagger && $(MAKE) install

uninstall:
	cd decoder && $(MAKE) uninstall
	cd deviceinfo && $(MAKE) uninstall
	cd dsp && $(MAKE) uninstall
	cd encoder && $(MAKE) uninstall
	cd extension && $(MAKE) uninstall
	cd other && $(MAKE) uninstall
	cd output && $(MAKE) uninstall
	cd tagger && $(MAKE) uninstall
