########## BoCA directory makefile ##########

all:
	cd decoder && $(MAKE)
	cd deviceinfo && $(MAKE)
	cd dsp && $(MAKE)
	cd encoder && $(MAKE)
	cd extension && $(MAKE)
	cd other && $(MAKE)
	cd output && $(MAKE)
	cd tagger && $(MAKE)

clean:
	cd decoder && $(MAKE) clean
	cd deviceinfo && $(MAKE) clean
	cd dsp && $(MAKE) clean
	cd encoder && $(MAKE) clean
	cd extension && $(MAKE) clean
	cd other && $(MAKE) clean
	cd output && $(MAKE) clean
	cd tagger && $(MAKE) clean
