########## BoCA directory makefile ##########

all:
	cd decoder && make
	cd deviceinfo && make
	cd dsp && make
	cd encoder && make
	cd extension && make
	cd other && make
	cd output && make
	cd tagger && make

clean:
	cd decoder && make clean
	cd deviceinfo && make clean
	cd dsp && make clean
	cd encoder && make clean
	cd extension && make clean
	cd other && make clean
	cd output && make clean
	cd tagger && make clean
