########## BoCA component makefile ##########

# Change these variables to fit your project:
TARGET	  = id3v2
TYPE	  = tagger
VERSION	  = 1.0

BOCA_PATH = ../../..

# Enter object files here:
OBJECTS	  = dllinterface.o id3v2_tag.o

# Enter additional defines here:
DEFINE	  = -DID3LIB_LINKOPTION=LINKOPTION_USE_DYNAMIC

# Enter additional library dependencies here:
LIBS	  =

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
CLEANCMD1 =
CLEANCMD1 =

## Do not change anything below this line. ##

include $(BOCA_PATH)/Makefile-directories
include $(BOCA_PATH)/Makefile-commands
