########## BoCA directory makefile ##########

BOCA_PATH = ../..

include $(BOCA_PATH)/Makefile-options

all:
	cd md5 && $(MAKE)

clean:
	cd md5 && $(MAKE) clean

install:
	cd md5 && $(MAKE) install

uninstall:
	cd md5 && $(MAKE) uninstall
