########## BoCA component makefile ##########

# Change these variables to fit your project:
TARGET	  = wma
TYPE	  = encoder
VERSION	  = 1.0

BOCA_PATH = ../../..

# Enter object files here:
OBJECTS	  = config.o dllinterface.o wma_out.o

# Enter additional defines here:
DEFINE	  =

# Enter additional library dependencies here:
LIBS	  = -lole32 -luuid -Xlinker --enable-stdcall-fixup

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
CLEANCMD1 =
CLEANCMD1 =

## Do not change anything below this line. ##

include $(BOCA_PATH)/Makefile-directories
include $(BOCA_PATH)/Makefile-commands
